name: Build Android

on:
  workflow_dispatch:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    strategy:
      matrix:
        arch: ["aarch64"]
      fail-fast: false

    name: "Build for ${{matrix.arch}}"

    runs-on: ubuntu-latest

    steps:        
      - uses: actions/checkout@main

      - name: Build
        run: |
          sudo apt update
          sudo apt install -y libxrandr-dev libxxf86vm-dev libxcb-*-dev libx11-xcb-dev libxfixes-dev libx11-dev
          pip3 install mako meson ninja
          export ANDROID_NDK_HOME="$ANDROID_SDK_ROOT/ndk-bundle"
          envsubst <android-drm-${{matrix.arch}} >build-crossfile-drm
          git clone --depth 1 https://gitlab.freedesktop.org/mesa/drm.git
          cd drm
          meson setup "build-android" \
            --prefix=/tmp/drm-static \
            --cross-file "../build-crossfile-drm" \
            -Ddefault_library=static \
            -Dintel=disabled \
            -Dradeon=disabled \
            -Damdgpu=disabled \
            -Dnouveau=disabled \
            -Dvmwgfx=disabled \
            -Dfreedreno=disabled \
            -Dvc4=disabled \
            -Detnaviv=disabled \
            -Dfreedreno-kgsl=false
          ninja -C "build-android" install
          cd ..
          envsubst <android-${{matrix.arch}} >build-crossfile
          git clone --branch mesa-24.2.6 https://gitlab.freedesktop.org/mesa/mesa
          git clone --branch 24.2.6 https://github.com/Vera-Firefly/mesa-build-fix
          cp -rf mesa-build-fix/* mesa/
          cd mesa
          meson setup "build-android" \
            --prefix=/tmp/mesa \
            --cross-file "../build-crossfile" \
            -Dplatforms=android \
            -Dplatform-sdk-version=30 \
            -Dandroid-stub=true \
            -Dandroid-libbacktrace=disabled \
            -Dandroid-strict=false \
            -Dxlib-lease=disabled \
            -Degl=disabled \
            -Dgbm=disabled \
            -Dglx=disabled \
            -Dllvm=disabled \
            -Dopengl=true \
            -Dosmesa=true \
            -Dvulkan-drivers= \
            -Dgallium-drivers=zink \
            -Dshared-glapi=false \
            -Dbuildtype=release
          ninja -C "build-android" install
          cp /tmp/mesa/lib/libOSMesa.so.8.0.0 /tmp/mesa/lib/libOSMesa_8.so
      - name: Upload libraries
        uses: actions/upload-artifact@main
        with:
          name: libOSMesa_${{matrix.arch}}
          path: /tmp/mesa/lib/libOSMesa_8.so
